diseases_detected = [
    "Flu", "Common Cold", "Allergy", "Asthma", "Bronchitis", "Pneumonia", "Tuberculosis", "Sinusitis",
    "Malaria", "Dengue Fever", "Chikungunya", "Zika Virus", "Yellow Fever", "Ebola", "HIV/AIDS",
    "Hepatitis", "Chickenpox", "Measles", "Mumps", "Rubella", "Whooping Cough", "Typhoid Fever",
    "Cholera", "Dysentery", "Botulism", "E. coli Infection", "Salmonella Infection", "Lyme Disease",
    "Rabies", "Meningitis", "Encephalitis", "Parkinson's Disease", "Alzheimer's Disease", "Multiple Sclerosis",
    "Epilepsy", "Cerebral Palsy", "Huntington's Disease", "Down Syndrome", "Autism Spectrum Disorder",
    "Cancer", "Heart Disease", "Stroke", "Diabetes", "Hypertension", "Arthritis", "Osteoporosis",
    "Gout", "Anemia", "Hemophilia", "Leukemia", "Lymphoma", "Melanoma", "Psoriasis", "Eczema",
    "Acne", "Rosacea", "Vitiligo", "Fibromyalgia", "Chronic Fatigue Syndrome", "Endometriosis",
    "Polycystic Ovary Syndrome", "Fibroids", "Ovarian Cancer", "Cervical Cancer", "Breast Cancer",
    "Prostate Cancer", "Testicular Cancer", "Colon Cancer", "Kidney Stones", "Gallstones", "Appendicitis",
    "Ulcerative Colitis", "Crohn's Disease", "Irritable Bowel Syndrome", "GERD", "Cirrhosis",
    "Pancreatitis", "Peptic Ulcer", "Diverticulitis", "Hernia", "Glaucoma", "Cataracts", "Macular Degeneration",
    "Retinal Detachment", "Conjunctivitis", "Color Blindness", "Hearing Loss", "Tinnitus", "Meniere's Disease",
    "Otitis Media", "Vertigo", "Lupus", "Rheumatoid Arthritis", "Scleroderma", "Graves' Disease", "Hashimoto's Thyroiditis",
    "Gingivitis", "Periodontitis", "Oral Cancer", "Thrush", "Gastritis", "Peptic Ulcer", "Gastroenteritis",
    "Pancreatitis", "Appendicitis", "Hepatitis A", "Hepatitis B", "Hepatitis C", "Hepatitis D", "Hepatitis E",
    "Biliary Atresia", "Celiac Disease", "Crohn's Disease", "Colitis", "Irritable Bowel Syndrome", "Duodenal Atresia",
    "Intussusception", "Gastroesophageal Reflux Disease", "Stomach Cancer", "Esophageal Cancer", "Liver Cancer",
    "Pancreatic Cancer", "Gallbladder Cancer", "Small Intestine Cancer", "Colorectal Cancer", "Anal Cancer",
    "Hemorrhoids", "Anal Fissure", "Anal Fistula", "Pelvic Inflammatory Disease", "Endometriosis", "Ovarian Cysts",
    "Uterine Fibroids", "Endometrial Cancer", "Ovarian Cancer", "Cervical Cancer", "Vaginal Cancer", "Vulvar Cancer",
    "Testicular Torsion", "Epididymitis", "Varicocele", "Orchitis", "Hydrocele", "Testicular Cancer", "Prostatitis",
    "Benign Prostatic Hyperplasia", "Prostate Cancer", "Erectile Dysfunction", "Premature Ejaculation", "Penile Cancer",
    "Bladder Cancer", "Kidney Cancer", "Renal Failure", "Polycystic Kidney Disease", "Glomerulonephritis",
    "Urinary Tract Infection", "Interstitial Cystitis", "Urethritis", "Pyelonephritis", "Hydronephrosis", "Cystitis",
    "Gout", "Osteoarthritis", "Rheumatoid Arthritis", "Ankylosing Spondylitis", "Psoriatic Arthritis", "Fibromyalgia",
    "Polymyalgia Rheumatica", "Lupus", "Sjogren's Syndrome", "Scleroderma", "Vasculitis", "Polymyositis", "Dermatomyositis",
    "Giant Cell Arteritis", "Temporal Arteritis", "Kawasaki Disease", "Buerger's Disease", "Raynaud's Phenomenon", "Atherosclerosis",
    "Peripheral Artery Disease", "Varicose Veins", "Deep Vein Thrombosis", "Pulmonary Embolism", "Lymphedema", "Cellulitis",
    "Erysipelas", "Necrotizing Fasciitis", "Abscess", "Boils", "Furuncles", "Carbuncles", "Impetigo", "Scabies", "Lice",
    "Ringworm", "Athlete's Foot", "Nail Fungus", "Yeast Infection", "Herpes Simplex", "Shingles", "Genital Warts",
    "Chlamydia", "Gonorrhea", "Syphilis", "Trichomoniasis", "Human Papillomavirus", "HIV/AIDS", "Hepatitis B", "Hepatitis C",
    "Genital Herpes", "Pelvic Inflammatory Disease", "Cervicitis", "Vaginitis", "Vulvodynia", "Vulvar Cancer", "Ovarian Cancer",
    "Endometrial Cancer", "Uterine Cancer", "Cervical Cancer", "Testicular Cancer", "Penile Cancer", "Prostate Cancer",
    "Bladder Cancer", "Kidney Cancer", "Renal Cancer", "Adrenal Cancer", "Liver Cancer", "Gallbladder Cancer", "Pancreatic Cancer",
    "Gastrointestinal Stromal Tumors", "Sarcoma", "Melanoma", "Basal Cell Carcinoma", "Squamous Cell Carcinoma", "Non-Hodgkin Lymphoma",
    "Hodgkin Lymphoma", "Leukemia", "Multiple Myeloma", "Brain Tumors", "Spinal Cord Tumors", "Pituitary Tumors", "Thyroid Cancer",
    "Parathyroid Cancer", "Thymus Cancer", "Carcinoid Tumors", "Mesothelioma", "Wilms Tumor", "Neuroblastoma", "Retinoblastoma",
    "Ewing Sarcoma", "Osteosarcoma", "Chondrosarcoma", "Fibrosarcoma", "Rhabdomyosarcoma", "Angiosarcoma", "Kaposi Sarcoma",
    "Acoustic Neuroma", "Meningioma", "Gliomas", "Astrocytomas", "Oligodendroglioma", "Ependymomas", "Medulloblastoma",
    "Craniopharyngioma", "Pituitary Tumors", "Schwannomas", "Ganglioneuroma", "Ganglioneuroblastoma", "Neuroblastoma",
    "Retinoblastoma", "Hemangioblastoma", "Craniopharyngioma", "Pineal Tumors", "Chordoma", "Craniopharyngioma", "Meningioma",
    "Glioblastoma Multiforme", "Anaplastic Astrocytoma", "Oligodendroglioma", "Ependymoma", "Medulloblastoma", "Acoustic Neuroma",
    "Vestibular Schwannoma", "Meningioma", "Pituitary Adenoma", "Chordoma", "Pineal Tumors", "Germ Cell Tumors", "Pituitary Adenoma",
    "Craniopharyngioma", "Choroid Plexus Tumor", "Pineal Tumors", "Retinoblastoma", "Histiocytosis", "Osteochondroma",
    "Osteosarcoma", "Ewing Sarcoma", "Fibrosarcoma", "Chondrosarcoma", "Adamantinoma", "Desmoplastic Fibroma", "Giant Cell Tumor",
    "Aneurysmal Bone Cyst", "Leukemia", "Lymphoma", "Multiple Myeloma", "Thymoma", "Thymic Carcinoma", "Thymic Carcinoma",
    "Thymic Carcinoma", "Germ Cell Tumor", "Teratoma", "Dysgerminoma", "Endodermal Sinus Tumor", "Gonadoblastoma",
    "Polyembryoma", "Choriocarcinoma", "Embyronal Carcinoma", "Leukemia", "Lymphoma", "Neuroblastoma", "Rhabdomyosarcoma",
    "Retinoblastoma", "Wilms Tumor", "Medulloblastoma", "PNET", "Ewing Sarcoma", "Bone Cancer", "Soft Tissue Sarcoma",
    "Osteosarcoma", "Chondrosarcoma", "Chordoma", "Soft Tissue Sarcoma", "Rhabdomyosarcoma", "Fibrosarcoma", "Synovial Sarcoma",
    "Epithelioid Sarcoma", "Angiosarcoma", "Kaposi Sarcoma", "Malignant Peripheral Nerve Sheath Tumor", "Malignant Fibrous Histiocytoma",
    "Liposarcoma", "Leiomyosarcoma", "Gastrointestinal Stromal Tumor", "Mesenchymal Chondrosarcoma", "Clear Cell Sarcoma",
    "Alveolar Soft Part Sarcoma", "Desmoplastic Small Round Cell Tumor", "Peritoneal Mesothelioma", "Desmoid Tumor", "Undifferentiated Sarcoma",
    "Embryonal Sarcoma", "Ovarian Cancer", "Germ Cell Tumor", "Endometrioid Carcinoma", "Mucinous Carcinoma", "Clear Cell Carcinoma",
    "Granulosa Cell Tumor", "Dysgerminoma", "Immature Teratoma", "Yolk Sac Tumor", "Mixed Germ Cell Tumor", "Sex Cord-Stromal Tumor",
    "Fibrothecoma", "Brenner Tumor", "Ovarian Cancer", "Fallopian Tube Cancer", "Primary Peritoneal Cancer", "Cervical Cancer",
    "Endometrial Cancer", "Uterine Sarcoma", "Vaginal Cancer", "Vulvar Cancer", "Gestational Trophoblastic Disease",
    "Choriocarcinoma", "Hydatidiform Mole", "Placental Site Trophoblastic Tumor", "Epithelioid Trophoblastic Tumor",
    "Ovarian Cancer", "Cervical Cancer", "Endometrial Cancer", "Fallopian Tube Cancer", "Gestational Trophoblastic Disease",
    "Vaginal Cancer", "Vulvar Cancer", "Benign Breast Conditions", "Breast Cancer", "Benign Breast Conditions",
    "Benign Breast Conditions", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer",
    "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer",
    "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer",
    "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer",
    "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer",
    "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer",
    "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer",
    "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer",
    "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer",
    "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer",
    "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer",
    "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer",
    "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer",
    "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer",
    "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer",
    "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer",
    "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer",
    "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer",
    "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer",
    "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer",
    "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer",
    "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer",
    "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer",
    "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer",
    "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer",
    "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer",
    "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer",
    "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer",
    "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer",
    "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer",
    "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer",
    "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer",
    "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer",
    "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer",
    "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer",
    "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer",
    "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer",
    "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer",
    "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer",
    "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer",
    "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer",
    "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer",
    "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer",
    "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer",
    "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer",
    "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer",
    "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer", "Breast Cancer",
    "Breast Cancer"]